# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newsloaction',
            new_name='newslocation',
        ),
    ]
